# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'ubuntu-16.04'

variables:
  imageName: 'fplnotificator:$(Build.BuildId)'
  dockerId: 'FplRegistry'
  serverName: 'fplregistry.azurecr.io'
  dockerPassword: 
     
steps:
- script: |
    docker build -t $(serverName)/$(imageName) .
    docker login -u $(dockerId) -p $pswd $(serverName)
    docker push $(serverName)/$(imageName)
  env:
    pswd: $(dockerPassword)
        
      
